gitlab-server:
  image: gitlab/gitlab-ce:8.5.1-ce.0
  hostname: ${gitlab_hostname}
  ports:
  - 2289:22/tcp
  - 80:80/tcp
  - 443:443/tcp
  restart: always
  environment:
  - GITLAB_OMNIBUS_CONFIG="gitlab_rails['gitlab_shell_ssh_port'] = 2289;"
  volumes:
  - /srv/gitlab/config:/etc/gitlab
  - /srv/gitlab/logs:/var/log/gitlab
  - /srv/gitlab/reconfigure:/var/log/gitlab/reconfigure
  - /srv/gitlab/data:/var/opt/gitlab
